vim.cmd.cnoreabbrev({ 'W!', 'w!' })
vim.cmd.cnoreabbrev({ 'Q!', 'q!' })
vim.cmd.cnoreabbrev({ 'WQ', 'wq' })
vim.cmd.cnoreabbrev({ 'Wq', 'wq' })
vim.cmd.cnoreabbrev({ 'wQ', 'wq' })
vim.cmd.cnoreabbrev({ 'W', 'w' })
vim.cmd.cnoreabbrev({ 'Q', 'q' })
vim.cmd.cnoreabbrev({ 'c', 'colorscheme' })

vim.cmd('abb mason Mason')
vim.cmd('abb choat Choat')
vim.cmd('abb mvcvalli Mvcvalli')

vim.cmd('abb wwe WWE')
vim.cmd('abb aew AEW')
vim.cmd('abb njpw NJPW')
vim.cmd('abb nxt NXT')
vim.cmd('abb ufc UFC')
vim.cmd('abb mma MMA')

vim.cmd('abb discord Discord')
vim.cmd('abb twitter Twitter')
vim.cmd('abb instagram Instagram')
vim.cmd('abb facebook Facebook')
vim.cmd('abb reddit Reddit')
vim.cmd('abb youtube YouTube')
vim.cmd('abb github GitHub')
vim.cmd('abb gitlab GitLab')
vim.cmd('abb insta Instagram')
vim.cmd('abb lbry LBRY')
vim.cmd('abb odysee Odysee')
vim.cmd('abb fetlife FetLife')
vim.cmd('abb google Google')
vim.cmd('abb ddg DuckDuckGo')
vim.cmd('abb searx Searx')
vim.cmd('abb peertube PeerTube')

vim.cmd('abb sec second')
vim.cmd('abb secs seconds')
vim.cmd('abb min minute')
vim.cmd('abb mins minutes')

vim.cmd('abb ublock UBlock Origin')
vim.cmd('abb dots dotfiles')
vim.cmd('abb dir directory')
vim.cmd('abb nz New Zealand')
vim.cmd('abb NZ New Zealand')
vim.cmd('abb chch Christchurch')
vim.cmd('abb misc miscellaneous')
vim.cmd('abb Xmas Christmas')
vim.cmd('abb xmas Christmas')

vim.cmd('abb imo in my opinion')
vim.cmd('abb tbh to be honest')
vim.cmd('abb idk I don’t know')
vim.cmd('abb dm direct message')
vim.cmd('abb abt about')
vim.cmd('abb nvm never mind')
vim.cmd('abb ofc of course')

vim.cmd('abb monday Monday')
vim.cmd('abb tuesday Tuesday')
vim.cmd('abb wednesday Wednesday')
vim.cmd('abb thursday Thursday')
vim.cmd('abb friday Friday')
vim.cmd('abb saturday Saturday')
vim.cmd('abb sunday Sunday')
vim.cmd('abb january January')
vim.cmd('abb february February')
vim.cmd('abb march March')
vim.cmd('abb april April')
vim.cmd('abb may May')
vim.cmd('abb june June')
vim.cmd('abb july July')
vim.cmd('abb august August')
vim.cmd('abb september September')
vim.cmd('abb october October')
vim.cmd('abb november November')
vim.cmd('abb december December')

vim.cmd('abb bdsm BDSM')
vim.cmd('abb dd Domestic Discipline')
vim.cmd('abb dom Dominant')
vim.cmd('abb doms Dominant’s')
vim.cmd('abb sub Submissive')
vim.cmd('abb subs Submissive’s')
